"""Add photos table and remove sample_number

Revision ID: 6368217b4db3
Revises: dce6c24b5a19
Create Date: 2024-10-31 20:54:49.743152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6368217b4db3'
down_revision: Union[str, None] = 'dce6c24b5a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
